# Generated by Django 4.2.2 on 2023-07-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_collected',
            old_name='Uid',
            new_name='UID',
        ),
    ]
