# Generated by Django 4.2.2 on 2023-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_uid_data_collected_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_collected',
            name='period',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
