# Generated by Django 4.2.2 on 2023-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_data_collected_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_collected',
            name='period',
            field=models.IntegerField(null=True),
        ),
    ]
