# Generated by Django 4.2.2 on 2023-07-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_data_collected_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_collected',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='longitude',
        ),
    ]
