# Generated by Django 4.2.2 on 2023-08-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_data_collected_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_collected',
            name='user_agent',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
